fix serde feature use in hex module
ManevilleF/hexx pull request #100
Opened 2023-06-22 09:34 UTC by uvizhe

I found this while adding Reflect to Hex.

2023-06-22 11:06 UTC, ManevilleF requested changes
Thank you for your contribution !

One small request, and after that LGTM

2023-06-22 11:06 UTC, ManevilleF commented on src/lib.rs
> +//! - `hexx = { version = "0.8", features = ["bevy_reflect"] }`
```suggestion
//! - `hexx = { version = "0.7", features = ["bevy_reflect"] }`
```

This feature might be released for 0.7.1

2023-06-22 13:43 UTC, ManevilleF commented
> Shell I commit to a changelog as well?

The CI is failing because:
- You should add a CHANGELOG entry
- `rustfmt` is unhappy

2023-06-22 14:34 UTC, alice-i-cecile approved these changes
Very useful, and I firmly agree that this should be off by default.

2023-06-22 15:03 UTC, ManevilleF commented
> Very useful, and I firmly agree that this should be off by default.

When bevy reflection improves this wil probably be removed entirely and replaced by a bevy_hexx plugin

2023-06-22 16:59 UTC, uvizhe commented
Hmm, looks like adding `bevy_reflect` dev dependency solves the issue with mesh_builder example. Should I add it?

2023-06-23 08:37 UTC, ManevilleF commented
> Hmm, looks like adding `bevy_reflect` dev dependency solves the issue with mesh_builder example. Should I add it?
> 
> I'm not sure why there's a problem at all. I appreciate it if someone will explain it to me.

That's a weird issue, I cloned your branch and had no issue compiling the examples, I don't understand why this is happening either.
@alice-i-cecile Do you have any idea ?

2023-06-23 10:19 UTC, uvizhe commented
@ManevilleF have you tried to remove your Cargo.lock?

2023-06-23 12:40 UTC, alice-i-cecile commented
Yeah my guess is caching weirdness leading to inconsistent results.

2023-06-24 09:17 UTC, ManevilleF commented
@uvizhe could you try and rebase (or paply the changes of) #101  ? It seems #99 introduced a compilation problem which might be related to that issue with bevy_reflect

2023-06-24 21:17 UTC, ManevilleF requested changes
The `glam` feature is missing from `bevy_reflect`

2023-06-24 21:17 UTC, ManevilleF commented on Cargo.toml
> +default-features = false
```suggestion
default-features = false
features = ["glam"]
```

2023-06-25 09:26 UTC, ManevilleF approved these changes

2023-06-25 09:58 UTC, ManevilleF commented
I fixed the example and the missing feature. Everything should work now, I wait for the CI and I merge this

2023-06-25 10:12 UTC, merged