Bump Bevy to 0.15, glam to 0.29
ManevilleF/hexx pull request #181
Opened 2024-11-30 03:32 UTC by richchurcher

It's time for Bevy 0.15!

2024-11-30 03:48 UTC, richchurcher commented
(Er, slightly premature PR lol... more coming!)

2024-12-01 12:09 UTC, ManevilleF requested changes
Thank you very much for this PR ! Seeing how many changed bevy 0.15 brought I really appreciate the time you spent updating the examples.
I have 2 comment:
- I don't think `bevy_reflect` is needed for all the examples
- The material wrappers you added in some examples are not needed either, we can use the `MaterialMesh3d/2d` components directly

As you already spent time on this, I can handle the changes so let me know if you'd rather fix those comments yourself

2024-12-01 12:09 UTC, ManevilleF commented on Cargo.toml
> +required-features = ["bevy_reflect"]
Why require bevy_reflect for all examples ?

2024-12-01 12:09 UTC, ManevilleF commented on examples/3d_columns.rs
> +}
I don't think this type, added to most 3d examples is needed. we can keep storing a `Handle<StandardMaterial>` and instantiate a `MeshMaterial3d`

2024-12-01 12:09 UTC, ManevilleF commented on examples/3d_picking.rs
> +
Here again

2024-12-01 12:09 UTC, ManevilleF commented on examples/a_star.rs
> +
Same here, with `MeshMaterial2d`

2024-12-01 12:09 UTC, ManevilleF commented on examples/field_of_view.rs
> +
Again here

2024-12-01 12:09 UTC, ManevilleF commented on examples/hex_area.rs
> +
Again here

2024-12-01 12:09 UTC, ManevilleF commented on examples/hex_grid.rs
> +
Again here

2024-12-01 12:09 UTC, ManevilleF commented on examples/shapes.rs
>  #[derive(Resource)]
Again here

2024-12-01 12:09 UTC, ManevilleF commented on examples/wrap_map.rs
> +
Again here

2024-12-02 00:40 UTC, bas-ie commented on Cargo.toml
> +required-features = ["bevy_reflect"]
See below, enables wrapper components: but we could also go another way :slightly_smiling_face:

2024-12-02 00:48 UTC, bas-ie commented
Yes, apologies, I was playing around with patterns now that `Handle<T>` is no longer a component. I'll rework this now.

2024-12-02 01:48 UTC, bas-ie commented
There, that should be a bit better! Only thing we're still waiting on is a release for `bevy_inspector_egui`, after which I can update the examples that use it. I see they merged https://github.com/jakobhellermann/bevy-inspector-egui/commit/47f1cb6c5b63b47c40c9cbbd467422205319390e yesterday so they should be close!

2024-12-03 04:25 UTC, bas-ie commented
I think that's the last of it? Let me know if I missed anything.

2024-12-03 08:25 UTC, ManevilleF approved these changes
There is an issue with doctests I'll fix in a followup, seems unrelated to your work
LGTM !

2024-12-03 08:25 UTC, merged